import dynamic from 'next/dynamic';
import Head from 'next/head';

// Dynamically import components
const About = dynamic(() => import('@/components/About/About'));
const Archive = dynamic(() => import('@/components/Archive/Archive'));
const Client = dynamic(() => import('@/components/Client/Client'));
const Contact = dynamic(() => import('@/components/Contact/Contact'));
const Cookie = dynamic(() => import('@/components/Cookie/Cookie'));
const Footer = dynamic(() => import('@/components/Footer/Footer'));
const Services = dynamic(() => import('@/components/Services/Services'));
const Showreel = dynamic(() => import('@/components/Showreel/Showreel'));
const Work = dynamic(() => import('@/components/Work/Work'));
const Hero = dynamic(() => import('@/components/Hero/Hero'));

export default function Home() {
  return (
    <>
      <Head>
        <title>Philippe Layani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Showreel />
      <Work />
      <Archive />
      <Client />
      <Services />
      <About />
      <Contact />
      <Footer />
      <Cookie />
    </>
  );
}
